<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-R47CCG0J" failures="1" tests="6" name="testNgPack.Test1Class" time="8.784" errors="0" timestamp="10 Feb 2023 13:01:12 GMT" skipped="4">
  <testcase classname="testNgPack.Test1Class" name="test1" time="3.278">
    <failure message="The URL is not matched expected [https://www.firstnaukri.com/jobs-internship] but found [https://www.firstnaukri.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The URL is not matched expected [https://www.firstnaukri.com/jobs-internship] but found [https://www.firstnaukri.com/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at testNgPack.Test1Class.test1(Test1Class.java:90)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="testNgPack.Test1Class" name="test1" time="5.506"/>
  <testcase classname="testNgPack.Test1Class" name="test3">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="testNgPack.Test1Class" name="test3">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="testNgPack.Test1Class" name="test2">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="testNgPack.Test1Class" name="test2">
    <skipped/>
  </testcase> <!-- test2 -->
</testsuite> <!-- testNgPack.Test1Class -->
